SERVICES = [   {   'name': 'MIT Learn - Keycloak - Postgres',
        'description': '',
        'public_description': '',
        'notify_emails': [],
        'color': '#D7F5E1',
        'position': 28,
        'github_repository_name': '',
        'github_repository_branch': 'master',
        'gitlab_repository_branch': 'master',
        'environment_ids': ['afe3e34e-62e7-4534-bb4c-de57d24e6a59'],
        'service_ids': [   'c144023f-00c1-48dd-9e38-ad4c302207e3',
                           'b2389961-09be-4167-a304-a2ee1ef9af1b'],
        'owner_group_ids': ['9f00e9f1-2f13-470e-a856-50ab5003f260'],
        'owner_user_ids': [],
        'kubernetes_deployment_name': '',
        'alerts_email_enabled': False,
        'escalation_policy_id': '96629210-cc41-4e57-b059-b182a0f01c5b',
        'alert_broadcast_enabled': False,
        'incident_broadcast_enabled': False,
        'slack_channels': [],
        'slack_aliases': [],
        'alert_broadcast_channel': {},
        'incident_broadcast_channel': {}},
    {   'name': 'MIT Learn - Keycloak - Webapp',
        'description': '',
        'public_description': '',
        'notify_emails': [],
        'color': '#D7E7F5',
        'position': 27,
        'github_repository_name': '',
        'github_repository_branch': 'master',
        'gitlab_repository_branch': 'master',
        'environment_ids': ['afe3e34e-62e7-4534-bb4c-de57d24e6a59'],
        'service_ids': ['c144023f-00c1-48dd-9e38-ad4c302207e3'],
        'owner_group_ids': ['9f00e9f1-2f13-470e-a856-50ab5003f260'],
        'owner_user_ids': [],
        'kubernetes_deployment_name': '',
        'alerts_email_enabled': False,
        'escalation_policy_id': '96629210-cc41-4e57-b059-b182a0f01c5b',
        'alert_broadcast_enabled': False,
        'incident_broadcast_enabled': False,
        'slack_channels': [],
        'slack_aliases': [],
        'alert_broadcast_channel': {},
        'incident_broadcast_channel': {}},
    {   'name': 'ODL Video - Postgres',
        'description': '',
        'public_description': '',
        'notify_emails': [],
        'color': '#F5D9C4',
        'position': 26,
        'github_repository_name': '',
        'github_repository_branch': 'master',
        'gitlab_repository_branch': 'master',
        'environment_ids': ['afe3e34e-62e7-4534-bb4c-de57d24e6a59'],
        'service_ids': [   '9fc1b049-d60c-4a4c-b5d9-95ea8db3aae8',
                           'defb1faa-e8a4-4fe5-8f03-4103667592f1'],
        'owner_group_ids': ['9f00e9f1-2f13-470e-a856-50ab5003f260'],
        'owner_user_ids': [],
        'kubernetes_deployment_name': '',
        'alerts_email_enabled': False,
        'alert_broadcast_enabled': False,
        'incident_broadcast_enabled': False,
        'slack_channels': [],
        'slack_aliases': [],
        'alert_broadcast_channel': {},
        'incident_broadcast_channel': {}},
    {   'name': 'ODL Video - Celery',
        'description': '',
        'public_description': '',
        'notify_emails': [],
        'color': '#F5D9C4',
        'position': 25,
        'github_repository_name': '',
        'github_repository_branch': 'master',
        'gitlab_repository_branch': 'master',
        'environment_ids': ['afe3e34e-62e7-4534-bb4c-de57d24e6a59'],
        'service_ids': ['defb1faa-e8a4-4fe5-8f03-4103667592f1'],
        'owner_group_ids': ['9f00e9f1-2f13-470e-a856-50ab5003f260'],
        'owner_user_ids': [],
        'kubernetes_deployment_name': '',
        'alerts_email_enabled': False,
        'escalation_policy_id': '96629210-cc41-4e57-b059-b182a0f01c5b',
        'alert_broadcast_enabled': False,
        'incident_broadcast_enabled': False,
        'slack_channels': [],
        'slack_aliases': [],
        'alert_broadcast_channel': {},
        'incident_broadcast_channel': {}},
    {   'name': 'MIT Learn - Tika',
        'description': '',
        'public_description': '',
        'notify_emails': [],
        'color': '#FAEBB7',
        'position': 24,
        'github_repository_name': '',
        'github_repository_branch': 'master',
        'gitlab_repository_branch': 'master',
        'environment_ids': ['afe3e34e-62e7-4534-bb4c-de57d24e6a59'],
        'service_ids': [   '0e8c091d-274d-4687-bb70-d85c5600e90b',
                           '71bb3195-11a8-4a2d-b9b8-2b1dbbc5d6c2',
                           '7b46658d-cd59-4c49-970b-9e9dc8998a7e',
                           'b2389961-09be-4167-a304-a2ee1ef9af1b',
                           'cdceaa06-6690-4351-a3af-dd36bfd6fb55',
                           'c144023f-00c1-48dd-9e38-ad4c302207e3',
                           '70173c97-f29d-453f-93ea-da9321d5984d'],
        'owner_group_ids': ['9f00e9f1-2f13-470e-a856-50ab5003f260'],
        'owner_user_ids': [],
        'kubernetes_deployment_name': '',
        'alerts_email_enabled': False,
        'escalation_policy_id': '96629210-cc41-4e57-b059-b182a0f01c5b',
        'alert_broadcast_enabled': False,
        'incident_broadcast_enabled': False,
        'slack_channels': [],
        'slack_aliases': [],
        'alert_broadcast_channel': {},
        'incident_broadcast_channel': {}},
    {   'name': 'MIT Learn - Qdrant',
        'description': '',
        'public_description': '',
        'notify_emails': [],
        'color': '#FAEBB7',
        'position': 23,
        'github_repository_name': '',
        'github_repository_branch': 'master',
        'gitlab_repository_branch': 'master',
        'environment_ids': ['afe3e34e-62e7-4534-bb4c-de57d24e6a59'],
        'service_ids': [   '0e8c091d-274d-4687-bb70-d85c5600e90b',
                           '7b46658d-cd59-4c49-970b-9e9dc8998a7e',
                           'cdceaa06-6690-4351-a3af-dd36bfd6fb55',
                           'b2389961-09be-4167-a304-a2ee1ef9af1b',
                           'c144023f-00c1-48dd-9e38-ad4c302207e3',
                           '70173c97-f29d-453f-93ea-da9321d5984d'],
        'owner_group_ids': ['9f00e9f1-2f13-470e-a856-50ab5003f260'],
        'owner_user_ids': [],
        'kubernetes_deployment_name': '',
        'alerts_email_enabled': False,
        'escalation_policy_id': '96629210-cc41-4e57-b059-b182a0f01c5b',
        'alert_broadcast_enabled': False,
        'incident_broadcast_enabled': False,
        'slack_channels': [],
        'slack_aliases': [],
        'alert_broadcast_channel': {},
        'incident_broadcast_channel': {}},
    {   'name': 'MIT Learn - OpenSearch',
        'description': '',
        'public_description': '',
        'notify_emails': [],
        'color': '#D7F5E1',
        'position': 22,
        'github_repository_name': '',
        'github_repository_branch': 'master',
        'gitlab_repository_branch': 'master',
        'environment_ids': ['afe3e34e-62e7-4534-bb4c-de57d24e6a59'],
        'service_ids': [   '70173c97-f29d-453f-93ea-da9321d5984d',
                           'c144023f-00c1-48dd-9e38-ad4c302207e3',
                           '7b46658d-cd59-4c49-970b-9e9dc8998a7e',
                           '0e8c091d-274d-4687-bb70-d85c5600e90b'],
        'owner_group_ids': ['9f00e9f1-2f13-470e-a856-50ab5003f260'],
        'owner_user_ids': [],
        'kubernetes_deployment_name': '',
        'alerts_email_enabled': False,
        'escalation_policy_id': '96629210-cc41-4e57-b059-b182a0f01c5b',
        'alert_broadcast_enabled': False,
        'incident_broadcast_enabled': False,
        'slack_channels': [],
        'slack_aliases': [],
        'alert_broadcast_channel': {},
        'incident_broadcast_channel': {}},
    {   'name': 'MIT Learn - Postgres',
        'description': '',
        'public_description': '',
        'notify_emails': [],
        'color': '#D7F5E1',
        'position': 21,
        'github_repository_name': '',
        'github_repository_branch': 'master',
        'gitlab_repository_branch': 'master',
        'environment_ids': ['afe3e34e-62e7-4534-bb4c-de57d24e6a59'],
        'service_ids': [   '70173c97-f29d-453f-93ea-da9321d5984d',
                           'c144023f-00c1-48dd-9e38-ad4c302207e3',
                           'b2389961-09be-4167-a304-a2ee1ef9af1b',
                           '0e8c091d-274d-4687-bb70-d85c5600e90b'],
        'owner_group_ids': ['9f00e9f1-2f13-470e-a856-50ab5003f260'],
        'owner_user_ids': [],
        'kubernetes_deployment_name': '',
        'alerts_email_enabled': False,
        'escalation_policy_id': '96629210-cc41-4e57-b059-b182a0f01c5b',
        'alert_broadcast_enabled': False,
        'incident_broadcast_enabled': False,
        'slack_channels': [],
        'slack_aliases': [],
        'alert_broadcast_channel': {},
        'incident_broadcast_channel': {}},
    {   'name': 'MIT Learn - Redis',
        'description': '',
        'public_description': '',
        'notify_emails': [],
        'color': '#D7F5E1',
        'position': 20,
        'github_repository_name': '',
        'github_repository_branch': 'master',
        'gitlab_repository_branch': 'master',
        'environment_ids': ['afe3e34e-62e7-4534-bb4c-de57d24e6a59'],
        'service_ids': [   '70173c97-f29d-453f-93ea-da9321d5984d',
                           'c144023f-00c1-48dd-9e38-ad4c302207e3',
                           'b2389961-09be-4167-a304-a2ee1ef9af1b'],
        'owner_group_ids': ['9f00e9f1-2f13-470e-a856-50ab5003f260'],
        'owner_user_ids': [],
        'kubernetes_deployment_name': '',
        'alerts_email_enabled': False,
        'escalation_policy_id': '96629210-cc41-4e57-b059-b182a0f01c5b',
        'alert_broadcast_enabled': False,
        'incident_broadcast_enabled': False,
        'slack_channels': [],
        'slack_aliases': [],
        'alert_broadcast_channel': {},
        'incident_broadcast_channel': {}},
    {   'name': 'MIT Learn - NextJS',
        'description': '',
        'public_description': '',
        'notify_emails': [],
        'color': '#F5D9C4',
        'position': 19,
        'github_repository_name': '',
        'github_repository_branch': 'master',
        'gitlab_repository_branch': 'master',
        'environment_ids': ['afe3e34e-62e7-4534-bb4c-de57d24e6a59'],
        'service_ids': [   '70173c97-f29d-453f-93ea-da9321d5984d',
                           'c144023f-00c1-48dd-9e38-ad4c302207e3'],
        'owner_group_ids': ['9f00e9f1-2f13-470e-a856-50ab5003f260'],
        'owner_user_ids': [],
        'kubernetes_deployment_name': '',
        'alerts_email_enabled': False,
        'escalation_policy_id': '96629210-cc41-4e57-b059-b182a0f01c5b',
        'alert_broadcast_enabled': False,
        'incident_broadcast_enabled': False,
        'slack_channels': [],
        'slack_aliases': [],
        'alert_broadcast_channel': {},
        'incident_broadcast_channel': {}},
    {   'name': 'MITx Online - Open edX - OpenSearch',
        'description': '',
        'public_description': '',
        'notify_emails': [],
        'color': '#F4CFD1',
        'position': 18,
        'github_repository_name': '',
        'github_repository_branch': 'master',
        'gitlab_repository_branch': 'master',
        'environment_ids': ['afe3e34e-62e7-4534-bb4c-de57d24e6a59'],
        'service_ids': [   'db3e4db5-fa3f-4239-a0f4-aa558847df66',
                           'ce09f262-1edf-475f-b145-3185d0da7241',
                           '0f046ecc-a5eb-4cdf-aba2-6922001ad774',
                           '145db75f-c893-444b-9564-85ff41d42c6a',
                           '6ee39557-47af-40e9-a4f7-eccee9406ecf',
                           'ffd3bdea-a4f6-4f4a-a12a-f59e71f29fe9',
                           '24ef3748-0a12-4a55-9b4e-5eb94a08fe03',
                           '24abd4d9-4aac-4ea0-afc6-eb2106cc52fd'],
        'owner_group_ids': ['9f00e9f1-2f13-470e-a856-50ab5003f260'],
        'owner_user_ids': [],
        'kubernetes_deployment_name': '',
        'alerts_email_enabled': False,
        'escalation_policy_id': '96629210-cc41-4e57-b059-b182a0f01c5b',
        'alert_broadcast_enabled': False,
        'incident_broadcast_enabled': False,
        'slack_channels': [],
        'slack_aliases': [],
        'alert_broadcast_channel': {},
        'incident_broadcast_channel': {}},
    {   'name': 'MITx Online - Open edX - Redis',
        'description': '',
        'public_description': '',
        'notify_emails': [],
        'color': '#F4CFD1',
        'position': 17,
        'github_repository_name': '',
        'github_repository_branch': 'master',
        'gitlab_repository_branch': 'master',
        'environment_ids': [],
        'service_ids': [   'ce09f262-1edf-475f-b145-3185d0da7241',
                           '0f046ecc-a5eb-4cdf-aba2-6922001ad774',
                           '145db75f-c893-444b-9564-85ff41d42c6a',
                           '6ee39557-47af-40e9-a4f7-eccee9406ecf',
                           'db3e4db5-fa3f-4239-a0f4-aa558847df66'],
        'owner_group_ids': ['9f00e9f1-2f13-470e-a856-50ab5003f260'],
        'owner_user_ids': [],
        'kubernetes_deployment_name': '',
        'alerts_email_enabled': False,
        'escalation_policy_id': '96629210-cc41-4e57-b059-b182a0f01c5b',
        'alert_broadcast_enabled': False,
        'incident_broadcast_enabled': False,
        'slack_channels': [],
        'slack_aliases': [],
        'alert_broadcast_channel': {},
        'incident_broadcast_channel': {}},
    {   'name': 'MITx Online - Open edX - MongoDB',
        'description': '',
        'public_description': '',
        'notify_emails': [],
        'color': '#D7E7F5',
        'position': 16,
        'github_repository_name': '',
        'github_repository_branch': 'master',
        'gitlab_repository_branch': 'master',
        'environment_ids': ['afe3e34e-62e7-4534-bb4c-de57d24e6a59'],
        'service_ids': [   'ce09f262-1edf-475f-b145-3185d0da7241',
                           '0f046ecc-a5eb-4cdf-aba2-6922001ad774',
                           '145db75f-c893-444b-9564-85ff41d42c6a',
                           '6ee39557-47af-40e9-a4f7-eccee9406ecf'],
        'owner_group_ids': ['9f00e9f1-2f13-470e-a856-50ab5003f260'],
        'owner_user_ids': [],
        'kubernetes_deployment_name': '',
        'alerts_email_enabled': False,
        'escalation_policy_id': '96629210-cc41-4e57-b059-b182a0f01c5b',
        'alert_broadcast_enabled': False,
        'incident_broadcast_enabled': False,
        'slack_channels': [],
        'slack_aliases': [],
        'alert_broadcast_channel': {},
        'incident_broadcast_channel': {}},
    {   'name': 'MITx Online - Open edX - MySQL',
        'description': '',
        'public_description': '',
        'notify_emails': [],
        'color': '#F5D9C4',
        'position': 15,
        'github_repository_name': '',
        'github_repository_branch': 'master',
        'gitlab_repository_branch': 'master',
        'environment_ids': ['afe3e34e-62e7-4534-bb4c-de57d24e6a59'],
        'service_ids': [   'ce09f262-1edf-475f-b145-3185d0da7241',
                           '0f046ecc-a5eb-4cdf-aba2-6922001ad774',
                           '145db75f-c893-444b-9564-85ff41d42c6a',
                           '6ee39557-47af-40e9-a4f7-eccee9406ecf'],
        'owner_group_ids': ['9f00e9f1-2f13-470e-a856-50ab5003f260'],
        'owner_user_ids': [],
        'kubernetes_deployment_name': '',
        'alerts_email_enabled': False,
        'escalation_policy_id': '96629210-cc41-4e57-b059-b182a0f01c5b',
        'alert_broadcast_enabled': False,
        'incident_broadcast_enabled': False,
        'slack_channels': [],
        'slack_aliases': [],
        'alert_broadcast_channel': {},
        'incident_broadcast_channel': {}},
    {   'name': 'MITx Online - Open edX - CMS - Celery',
        'description': '',
        'public_description': '',
        'notify_emails': [],
        'color': '#F4CFD1',
        'position': 14,
        'github_repository_name': '',
        'github_repository_branch': 'master',
        'gitlab_repository_branch': 'master',
        'environment_ids': ['afe3e34e-62e7-4534-bb4c-de57d24e6a59'],
        'service_ids': [   '0f046ecc-a5eb-4cdf-aba2-6922001ad774',
                           'db3e4db5-fa3f-4239-a0f4-aa558847df66'],
        'owner_group_ids': ['9f00e9f1-2f13-470e-a856-50ab5003f260'],
        'owner_user_ids': [],
        'kubernetes_deployment_name': '',
        'alerts_email_enabled': False,
        'escalation_policy_id': '96629210-cc41-4e57-b059-b182a0f01c5b',
        'alert_broadcast_enabled': False,
        'incident_broadcast_enabled': False,
        'slack_channels': [],
        'slack_aliases': [],
        'alert_broadcast_channel': {},
        'incident_broadcast_channel': {}},
    {   'name': 'MITx Online - Open edX - CMS - Webapp',
        'description': '',
        'public_description': '',
        'notify_emails': [],
        'color': '#F5D9C4',
        'position': 13,
        'github_repository_name': '',
        'github_repository_branch': 'master',
        'gitlab_repository_branch': 'master',
        'environment_ids': ['afe3e34e-62e7-4534-bb4c-de57d24e6a59'],
        'service_ids': [   '145db75f-c893-444b-9564-85ff41d42c6a',
                           '6ee39557-47af-40e9-a4f7-eccee9406ecf'],
        'owner_group_ids': ['9f00e9f1-2f13-470e-a856-50ab5003f260'],
        'owner_user_ids': [],
        'kubernetes_deployment_name': '',
        'alerts_email_enabled': False,
        'escalation_policy_id': '96629210-cc41-4e57-b059-b182a0f01c5b',
        'alert_broadcast_enabled': False,
        'incident_broadcast_enabled': False,
        'slack_channels': [],
        'slack_aliases': [],
        'alert_broadcast_channel': {},
        'incident_broadcast_channel': {}},
    {   'name': 'MITx Online - Open edX - LMS - Celery',
        'description': '',
        'public_description': '',
        'notify_emails': [],
        'color': '#FAEBB7',
        'position': 12,
        'github_repository_name': '',
        'github_repository_branch': 'master',
        'gitlab_repository_branch': 'master',
        'environment_ids': ['afe3e34e-62e7-4534-bb4c-de57d24e6a59'],
        'service_ids': ['6ee39557-47af-40e9-a4f7-eccee9406ecf'],
        'owner_group_ids': ['9f00e9f1-2f13-470e-a856-50ab5003f260'],
        'owner_user_ids': [],
        'kubernetes_deployment_name': '',
        'alerts_email_enabled': False,
        'escalation_policy_id': '96629210-cc41-4e57-b059-b182a0f01c5b',
        'alert_broadcast_enabled': False,
        'incident_broadcast_enabled': False,
        'slack_channels': [],
        'slack_aliases': [],
        'alert_broadcast_channel': {},
        'incident_broadcast_channel': {}},
    {   'name': 'MIT Learn AI - Redis',
        'description': '',
        'public_description': '',
        'notify_emails': [],
        'color': '#F5D9C4',
        'position': 11,
        'github_repository_name': '',
        'github_repository_branch': 'master',
        'gitlab_repository_branch': 'master',
        'environment_ids': ['afe3e34e-62e7-4534-bb4c-de57d24e6a59'],
        'service_ids': [   '964321a2-ebd8-46d4-bd9e-c582cb4e4e49',
                           'dfc02e84-e281-43a6-b340-0e7cadd62036',
                           'aefc0e95-1376-41f2-b102-335a186e9eb7'],
        'owner_group_ids': ['9f00e9f1-2f13-470e-a856-50ab5003f260'],
        'owner_user_ids': [],
        'kubernetes_deployment_name': '',
        'alerts_email_enabled': False,
        'escalation_policy_id': '96629210-cc41-4e57-b059-b182a0f01c5b',
        'alert_broadcast_enabled': False,
        'incident_broadcast_enabled': False,
        'slack_channels': [],
        'slack_aliases': [],
        'alert_broadcast_channel': {},
        'incident_broadcast_channel': {}},
    {   'name': 'MIT Learn AI - Postgres',
        'description': '',
        'public_description': '',
        'notify_emails': [],
        'color': '#FAEBB7',
        'position': 10,
        'github_repository_name': '',
        'github_repository_branch': 'master',
        'gitlab_repository_branch': 'master',
        'environment_ids': ['afe3e34e-62e7-4534-bb4c-de57d24e6a59'],
        'service_ids': [   '964321a2-ebd8-46d4-bd9e-c582cb4e4e49',
                           'dfc02e84-e281-43a6-b340-0e7cadd62036'],
        'owner_group_ids': ['9f00e9f1-2f13-470e-a856-50ab5003f260'],
        'owner_user_ids': [],
        'kubernetes_deployment_name': '',
        'alerts_email_enabled': False,
        'escalation_policy_id': '96629210-cc41-4e57-b059-b182a0f01c5b',
        'alert_broadcast_enabled': False,
        'incident_broadcast_enabled': False,
        'slack_channels': [],
        'slack_aliases': [],
        'alert_broadcast_channel': {},
        'incident_broadcast_channel': {}},
    {   'name': 'MIT Learn AI - Celery',
        'description': '',
        'public_description': '',
        'notify_emails': [],
        'color': '#FAEBB7',
        'position': 9,
        'github_repository_name': '',
        'github_repository_branch': 'master',
        'gitlab_repository_branch': 'master',
        'environment_ids': ['afe3e34e-62e7-4534-bb4c-de57d24e6a59'],
        'service_ids': ['dfc02e84-e281-43a6-b340-0e7cadd62036'],
        'owner_group_ids': ['9f00e9f1-2f13-470e-a856-50ab5003f260'],
        'owner_user_ids': [],
        'kubernetes_deployment_name': '',
        'alerts_email_enabled': False,
        'escalation_policy_id': '96629210-cc41-4e57-b059-b182a0f01c5b',
        'alert_broadcast_enabled': False,
        'incident_broadcast_enabled': False,
        'slack_channels': [],
        'slack_aliases': [],
        'alert_broadcast_channel': {},
        'incident_broadcast_channel': {}},
    {   'name': 'MITx Online - Django - Webapp',
        'description': '',
        'public_description': '',
        'notify_emails': [],
        'color': '#F4CFD1',
        'position': 8,
        'github_repository_name': '',
        'github_repository_branch': 'master',
        'gitlab_repository_branch': 'master',
        'environment_ids': [],
        'service_ids': [   'db3e4db5-fa3f-4239-a0f4-aa558847df66',
                           'ce09f262-1edf-475f-b145-3185d0da7241',
                           '0f046ecc-a5eb-4cdf-aba2-6922001ad774',
                           '145db75f-c893-444b-9564-85ff41d42c6a',
                           '6ee39557-47af-40e9-a4f7-eccee9406ecf',
                           'ffd3bdea-a4f6-4f4a-a12a-f59e71f29fe9',
                           '24ef3748-0a12-4a55-9b4e-5eb94a08fe03',
                           '24abd4d9-4aac-4ea0-afc6-eb2106cc52fd'],
        'owner_group_ids': ['9f00e9f1-2f13-470e-a856-50ab5003f260'],
        'owner_user_ids': [],
        'kubernetes_deployment_name': '',
        'alerts_email_enabled': False,
        'escalation_policy_id': '96629210-cc41-4e57-b059-b182a0f01c5b',
        'alert_broadcast_enabled': False,
        'incident_broadcast_enabled': False,
        'slack_channels': [],
        'slack_aliases': [],
        'alert_broadcast_channel': {},
        'incident_broadcast_channel': {}},
    {   'name': 'MIT Learn - Celery',
        'description': '',
        'public_description': '',
        'notify_emails': [],
        'color': '#FAEBB7',
        'position': 7,
        'github_repository_name': '',
        'github_repository_branch': 'master',
        'gitlab_repository_branch': 'master',
        'environment_ids': ['afe3e34e-62e7-4534-bb4c-de57d24e6a59'],
        'service_ids': ['c144023f-00c1-48dd-9e38-ad4c302207e3'],
        'owner_group_ids': ['9f00e9f1-2f13-470e-a856-50ab5003f260'],
        'owner_user_ids': [],
        'kubernetes_deployment_name': '',
        'alerts_email_enabled': False,
        'escalation_policy_id': '96629210-cc41-4e57-b059-b182a0f01c5b',
        'alert_broadcast_enabled': False,
        'incident_broadcast_enabled': False,
        'slack_channels': [],
        'slack_aliases': [],
        'alert_broadcast_channel': {},
        'incident_broadcast_channel': {}},
    {   'name': 'ODL Video - Django - Webapp',
        'description': '',
        'public_description': '',
        'notify_emails': [],
        'color': '#D7E7F5',
        'position': 6,
        'github_repository_name': '',
        'github_repository_branch': 'master',
        'gitlab_repository_branch': 'master',
        'environment_ids': ['afe3e34e-62e7-4534-bb4c-de57d24e6a59'],
        'service_ids': [],
        'owner_group_ids': ['9f00e9f1-2f13-470e-a856-50ab5003f260'],
        'owner_user_ids': [],
        'kubernetes_deployment_name': '',
        'alerts_email_enabled': False,
        'escalation_policy_id': '96629210-cc41-4e57-b059-b182a0f01c5b',
        'alert_broadcast_enabled': False,
        'incident_broadcast_enabled': False,
        'slack_channels': [],
        'slack_aliases': [],
        'alert_broadcast_channel': {},
        'incident_broadcast_channel': {}},
    {   'name': 'MIT Learn AI - Django - Webapp',
        'description': '',
        'public_description': '',
        'notify_emails': [],
        'color': '#FAEBB7',
        'position': 5,
        'github_repository_name': '',
        'github_repository_branch': 'master',
        'gitlab_repository_branch': 'master',
        'environment_ids': ['afe3e34e-62e7-4534-bb4c-de57d24e6a59'],
        'service_ids': [],
        'owner_group_ids': ['9f00e9f1-2f13-470e-a856-50ab5003f260'],
        'owner_user_ids': [],
        'kubernetes_deployment_name': '',
        'alerts_email_enabled': False,
        'escalation_policy_id': '96629210-cc41-4e57-b059-b182a0f01c5b',
        'alert_broadcast_enabled': False,
        'incident_broadcast_enabled': False,
        'slack_channels': [],
        'slack_aliases': [],
        'alert_broadcast_channel': {},
        'incident_broadcast_channel': {}},
    {   'name': 'MITx Online - Open edX - LMS - Webapp',
        'description': '',
        'public_description': '',
        'notify_emails': [],
        'color': '#F5D9C4',
        'position': 4,
        'github_repository_name': '',
        'github_repository_branch': 'master',
        'gitlab_repository_branch': 'master',
        'environment_ids': [],
        'service_ids': [],
        'owner_group_ids': ['9f00e9f1-2f13-470e-a856-50ab5003f260'],
        'owner_user_ids': [],
        'kubernetes_deployment_name': '',
        'alerts_email_enabled': False,
        'escalation_policy_id': '96629210-cc41-4e57-b059-b182a0f01c5b',
        'alert_broadcast_enabled': False,
        'incident_broadcast_enabled': False,
        'slack_channels': [],
        'slack_aliases': [],
        'alert_broadcast_channel': {},
        'incident_broadcast_channel': {}},
    {   'name': 'MIT Learn - Django - Webapp',
        'description': 'The MIT Learn Django application',
        'public_description': '',
        'notify_emails': [],
        'color': '#F4CFD1',
        'position': 3,
        'github_repository_name': '',
        'github_repository_branch': 'master',
        'gitlab_repository_branch': 'master',
        'environment_ids': [],
        'service_ids': [],
        'owner_group_ids': ['9f00e9f1-2f13-470e-a856-50ab5003f260'],
        'owner_user_ids': [],
        'kubernetes_deployment_name': '',
        'alerts_email_enabled': False,
        'escalation_policy_id': '96629210-cc41-4e57-b059-b182a0f01c5b',
        'alert_broadcast_enabled': False,
        'incident_broadcast_enabled': False,
        'slack_channels': [],
        'slack_aliases': [],
        'alert_broadcast_channel': {},
        'incident_broadcast_channel': {}},
    {   'name': 'CatchAll',
        'description': 'A catch-all service for managing the bucket of on-call '
                       'alerts',
        'public_description': '',
        'notify_emails': [],
        'color': '#F4CFD1',
        'position': 2,
        'github_repository_name': '',
        'github_repository_branch': 'master',
        'gitlab_repository_branch': 'master',
        'environment_ids': [],
        'service_ids': [],
        'owner_group_ids': ['9f00e9f1-2f13-470e-a856-50ab5003f260'],
        'owner_user_ids': [],
        'kubernetes_deployment_name': '',
        'alerts_email_enabled': False,
        'alert_urgency_id': '5d357977-9dbe-42ad-b647-5a442cab3d96',
        'escalation_policy_id': '96629210-cc41-4e57-b059-b182a0f01c5b',
        'alert_broadcast_enabled': False,
        'incident_broadcast_enabled': False,
        'slack_channels': [],
        'slack_aliases': [],
        'alert_broadcast_channel': {},
        'incident_broadcast_channel': {}},
    {   'name': 'UI - User Profile Block',
        'description': 'Displays user details.',
        'public_description': 'User Profile UI Block',
        'notify_emails': [],
        'color': '#D7E7F5',
        'position': 1,
        'github_repository_branch': 'master',
        'gitlab_repository_branch': 'master',
        'environment_ids': [],
        'service_ids': [],
        'owner_group_ids': [],
        'owner_user_ids': [],
        'alerts_email_enabled': False,
        'alert_broadcast_enabled': False,
        'incident_broadcast_enabled': False,
        'slack_channels': [],
        'slack_aliases': [],
        'alert_broadcast_channel': {},
        'incident_broadcast_channel': {}},
    {   'name': 'API - Authentication',
        'description': '/api/v1/authentication',
        'public_description': 'Authentications API',
        'notify_emails': [],
        'color': '#FAEBB7',
        'position': 1,
        'github_repository_branch': 'master',
        'gitlab_repository_branch': 'master',
        'environment_ids': [],
        'service_ids': [],
        'owner_group_ids': [],
        'owner_user_ids': [],
        'alerts_email_enabled': False,
        'alert_broadcast_enabled': False,
        'incident_broadcast_enabled': False,
        'slack_channels': [],
        'slack_aliases': [],
        'alert_broadcast_channel': {},
        'incident_broadcast_channel': {}}]

ROLES = [   {   'name': 'owner',
        'slug': 'owner',
        'alerts_permissions': ['create', 'read'],
        'api_keys_permissions': ['create', 'update', 'read', 'delete'],
        'audits_permissions': ['read'],
        'billing_permissions': ['update'],
        'environments_permissions': ['create', 'read', 'update', 'delete'],
        'form_fields_permissions': ['create', 'read', 'update', 'delete'],
        'functionalities_permissions': ['create', 'read', 'update', 'delete'],
        'groups_permissions': ['create', 'read', 'update', 'delete'],
        'incident_causes_permissions': ['create', 'read', 'update', 'delete'],
        'incident_feedbacks_permissions': ['read', 'create', 'update'],
        'incident_roles_permissions': ['create', 'read', 'update', 'delete'],
        'incident_types_permissions': ['create', 'read', 'update', 'delete'],
        'incidents_permissions': ['create', 'read', 'update', 'delete'],
        'integrations_permissions': ['create', 'read', 'update', 'delete'],
        'invitations_permissions': ['create', 'read', 'update', 'delete'],
        'playbooks_permissions': ['create', 'read', 'update', 'delete'],
        'private_incidents_permissions': ['create', 'read', 'update', 'delete'],
        'pulses_permissions': ['create', 'update', 'read'],
        'retrospective_permissions': ['create', 'read', 'update', 'delete'],
        'roles_permissions': ['create', 'read', 'update', 'delete'],
        'secrets_permissions': ['create', 'read', 'update', 'delete'],
        'services_permissions': ['create', 'read', 'update', 'delete'],
        'severities_permissions': ['create', 'read', 'update', 'delete'],
        'status_pages_permissions': ['create', 'read', 'update', 'delete'],
        'webhooks_permissions': ['create', 'read', 'update', 'delete'],
        'workflows_permissions': ['create', 'read', 'update', 'delete']},
    {   'name': 'user',
        'slug': 'user',
        'incident_permission_set_id': '3bc47de8-5079-4110-8e47-c7ff58f109d9',
        'alerts_permissions': ['create', 'read'],
        'api_keys_permissions': ['create', 'update', 'read', 'delete'],
        'environments_permissions': ['create', 'read', 'update', 'delete'],
        'form_fields_permissions': ['create', 'read', 'update', 'delete'],
        'functionalities_permissions': ['create', 'read', 'update', 'delete'],
        'groups_permissions': ['create', 'read', 'update', 'delete'],
        'incident_causes_permissions': ['create', 'read', 'update', 'delete'],
        'incident_feedbacks_permissions': ['read', 'create', 'update'],
        'incident_roles_permissions': ['create', 'read', 'update', 'delete'],
        'incident_types_permissions': ['create', 'read', 'update', 'delete'],
        'incidents_permissions': ['create', 'read', 'update', 'delete'],
        'invitations_permissions': ['create', 'read', 'update', 'delete'],
        'playbooks_permissions': ['create', 'read', 'update', 'delete'],
        'pulses_permissions': ['create', 'update', 'read'],
        'retrospective_permissions': ['create', 'read', 'update', 'delete'],
        'secrets_permissions': ['create', 'read', 'update', 'delete'],
        'services_permissions': ['create', 'read', 'update', 'delete'],
        'severities_permissions': ['create', 'read', 'update', 'delete'],
        'status_pages_permissions': ['create', 'read', 'update', 'delete'],
        'workflows_permissions': ['create', 'read', 'update', 'delete']},
    {   'name': 'observer',
        'slug': 'observer',
        'incident_permission_set_id': 'b7fc1246-fe14-4a9d-84d0-c2e8b5b15e54',
        'alerts_permissions': ['create', 'read'],
        'api_keys_permissions': ['read'],
        'environments_permissions': ['read'],
        'form_fields_permissions': ['read'],
        'functionalities_permissions': ['read'],
        'groups_permissions': ['read'],
        'incident_causes_permissions': ['read'],
        'incident_feedbacks_permissions': ['read'],
        'incident_roles_permissions': ['read'],
        'incident_types_permissions': ['read'],
        'incidents_permissions': ['read', 'create'],
        'invitations_permissions': ['read'],
        'playbooks_permissions': ['read'],
        'pulses_permissions': ['create', 'update', 'read'],
        'retrospective_permissions': ['read'],
        'services_permissions': ['read'],
        'severities_permissions': ['read'],
        'status_pages_permissions': ['read'],
        'workflows_permissions': ['read']},
    {'name': 'None', 'slug': 'no_access'},
    {   'name': 'admin',
        'slug': 'admin',
        'alerts_permissions': ['create', 'read'],
        'api_keys_permissions': ['create', 'update', 'read', 'delete'],
        'audits_permissions': ['read'],
        'environments_permissions': ['create', 'read', 'update', 'delete'],
        'form_fields_permissions': ['create', 'read', 'update', 'delete'],
        'functionalities_permissions': ['create', 'read', 'update', 'delete'],
        'groups_permissions': ['create', 'read', 'update', 'delete'],
        'incident_causes_permissions': ['create', 'read', 'update', 'delete'],
        'incident_feedbacks_permissions': ['read', 'create', 'update'],
        'incident_roles_permissions': ['create', 'read', 'update', 'delete'],
        'incident_types_permissions': ['create', 'read', 'update', 'delete'],
        'incidents_permissions': ['create', 'read', 'update', 'delete'],
        'integrations_permissions': ['create', 'read', 'update', 'delete'],
        'invitations_permissions': ['create', 'read', 'update', 'delete'],
        'playbooks_permissions': ['create', 'read', 'update', 'delete'],
        'private_incidents_permissions': ['create', 'read', 'update', 'delete'],
        'pulses_permissions': ['create', 'update', 'read'],
        'retrospective_permissions': ['create', 'read', 'update', 'delete'],
        'roles_permissions': ['create', 'read', 'update', 'delete'],
        'secrets_permissions': ['create', 'read', 'update', 'delete'],
        'services_permissions': ['create', 'read', 'update', 'delete'],
        'severities_permissions': ['create', 'read', 'update', 'delete'],
        'status_pages_permissions': ['create', 'read', 'update', 'delete'],
        'webhooks_permissions': ['create', 'read', 'update', 'delete'],
        'workflows_permissions': ['create', 'read', 'update', 'delete']}]

TEAMS = [   {   'name': 'ChrisTestTeam',
        'description': "Chris Patti's Test team. If this is sitting around "
                       'much beyond winter 2026 feel free to delete.',
        'notify_emails': [],
        'color': '#F5D9C4',
        'position': 2,
        'user_ids': [100683],
        'admin_ids': [100683],
        'alerts_email_enabled': False,
        'alert_broadcast_enabled': False,
        'incident_broadcast_enabled': False,
        'auto_add_members_when_attached': False,
        'slack_channels': [],
        'slack_aliases': [],
        'alert_broadcast_channel': {},
        'incident_broadcast_channel': {}},
    {   'name': 'Platform Engineering',
        'description': 'The go-to team for all incidents.',
        'notify_emails': [],
        'color': '#F5D9C4',
        'position': 1,
        'user_ids': [99415, 100683, 103372, 103392],
        'admin_ids': [],
        'alerts_email_enabled': True,
        'alert_urgency_id': '5d357977-9dbe-42ad-b647-5a442cab3d96',
        'alert_broadcast_enabled': False,
        'incident_broadcast_enabled': False,
        'auto_add_members_when_attached': True,
        'slack_channels': [],
        'slack_aliases': [],
        'alert_broadcast_channel': {},
        'incident_broadcast_channel': {}}]

ALERT_SOURCES = [   {   'name': 'MITOL Sentry',
        'source_type': 'sentry',
        'alert_urgency_id': 'd7ed8e91-ffa9-4cc4-b524-729d14a4425b',
        'deduplicate_alerts_by_key': False,
        'deduplication_key_kind': 'payload',
        'deduplication_key_path': None,
        'deduplication_key_regexp': None,
        'owner_group_ids': [],
        'alert_template_attributes': {   'title': '{{ '
                                                  'alert.data.data.issue.title '
                                                  '}}',
                                         'description': 'An alert has been '
                                                        'triggered from {{ '
                                                        'alert.data.data.metric_alert.projects[0] '
                                                        '}}:\n'
                                                        '{{ '
                                                        'alert.data.data.description_text '
                                                        '}}',
                                         'external_url': '{{  '
                                                         'alert.data.data.web_url '
                                                         '}}'},
        'alert_source_urgency_rules_attributes': [   {   'json_path': '$.data.action',
                                                         'operator': 'is_not',
                                                         'value': 'critical',
                                                         'kind': 'payload',
                                                         'alert_urgency_id': 'd7ed8e91-ffa9-4cc4-b524-729d14a4425b'}],
        'sourceable_attributes': None,
        'resolution_rule_attributes': None,
        'alert_source_fields_attributes': [   {   'alert_field_id': '4a3add3c-5611-4dd9-ba65-4fb60b7f4fc6',
                                                  'template_body': 'An alert '
                                                                   'has been '
                                                                   'triggered '
                                                                   'from {{ '
                                                                   'alert.data.data.metric_alert.projects[0] '
                                                                   '}}:\n'
                                                                   '{{ '
                                                                   'alert.data.data.description_text '
                                                                   '}}'},
                                              {   'alert_field_id': '45a09cf3-b0f2-43cf-b596-34aaab9279dc',
                                                  'template_body': '{{  '
                                                                   'alert.data.data.web_url '
                                                                   '}}'},
                                              {   'alert_field_id': '39b50c54-efa8-47fc-acc6-90f1455a8834',
                                                  'template_body': '{{ '
                                                                   'alert.data.data.issue.title '
                                                                   '}}'}]},
    {   'name': 'Grafana Prometheus - CI',
        'source_type': 'alertmanager',
        'alert_urgency_id': '5d357977-9dbe-42ad-b647-5a442cab3d96',
        'deduplicate_alerts_by_key': False,
        'deduplication_key_kind': 'payload',
        'deduplication_key_path': None,
        'deduplication_key_regexp': None,
        'owner_group_ids': [],
        'alert_template_attributes': None,
        'alert_source_urgency_rules_attributes': [],
        'sourceable_attributes': None,
        'resolution_rule_attributes': None,
        'alert_source_fields_attributes': [   {   'alert_field_id': '39b50c54-efa8-47fc-acc6-90f1455a8834',
                                                  'template_body': None},
                                              {   'alert_field_id': '4a3add3c-5611-4dd9-ba65-4fb60b7f4fc6',
                                                  'template_body': None},
                                              {   'alert_field_id': '45a09cf3-b0f2-43cf-b596-34aaab9279dc',
                                                  'template_body': None}]},
    {   'name': 'Grafana Prometheus - QA',
        'source_type': 'alertmanager',
        'alert_urgency_id': 'fce5c971-6660-4ad9-90eb-e75122055f50',
        'deduplicate_alerts_by_key': False,
        'deduplication_key_kind': 'payload',
        'deduplication_key_path': None,
        'deduplication_key_regexp': None,
        'owner_group_ids': [],
        'alert_template_attributes': None,
        'alert_source_urgency_rules_attributes': [],
        'sourceable_attributes': None,
        'resolution_rule_attributes': None,
        'alert_source_fields_attributes': [   {   'alert_field_id': '39b50c54-efa8-47fc-acc6-90f1455a8834',
                                                  'template_body': None},
                                              {   'alert_field_id': '4a3add3c-5611-4dd9-ba65-4fb60b7f4fc6',
                                                  'template_body': None},
                                              {   'alert_field_id': '45a09cf3-b0f2-43cf-b596-34aaab9279dc',
                                                  'template_body': None}]},
    {   'name': 'Grafana Prometheus - Production',
        'source_type': 'alertmanager',
        'alert_urgency_id': '5d357977-9dbe-42ad-b647-5a442cab3d96',
        'deduplicate_alerts_by_key': False,
        'deduplication_key_kind': 'payload',
        'deduplication_key_path': None,
        'deduplication_key_regexp': None,
        'owner_group_ids': [],
        'alert_template_attributes': None,
        'alert_source_urgency_rules_attributes': [   {   'json_path': '$.commonLabels.severity',
                                                         'operator': 'is',
                                                         'value': 'warning',
                                                         'kind': 'payload',
                                                         'alert_urgency_id': 'd7ed8e91-ffa9-4cc4-b524-729d14a4425b'}],
        'sourceable_attributes': None,
        'resolution_rule_attributes': None,
        'alert_source_fields_attributes': [   {   'alert_field_id': '39b50c54-efa8-47fc-acc6-90f1455a8834',
                                                  'template_body': None},
                                              {   'alert_field_id': '4a3add3c-5611-4dd9-ba65-4fb60b7f4fc6',
                                                  'template_body': None},
                                              {   'alert_field_id': '45a09cf3-b0f2-43cf-b596-34aaab9279dc',
                                                  'template_body': None}]},
    {   'accept_threaded_emails': False,
        'name': 'Platform Engineering Team Email Monitor',
        'source_type': 'email',
        'alert_urgency_id': '5d357977-9dbe-42ad-b647-5a442cab3d96',
        'deduplicate_alerts_by_key': False,
        'deduplication_key_kind': 'payload',
        'deduplication_key_path': None,
        'deduplication_key_regexp': None,
        'owner_group_ids': ['9f00e9f1-2f13-470e-a856-50ab5003f260'],
        'alert_template_attributes': {   'title': None,
                                         'description': '{{ '
                                                        'alert.data.email.body '
                                                        '}}',
                                         'external_url': None},
        'alert_source_urgency_rules_attributes': [],
        'sourceable_attributes': None,
        'resolution_rule_attributes': None,
        'alert_source_fields_attributes': [   {   'alert_field_id': '39b50c54-efa8-47fc-acc6-90f1455a8834',
                                                  'template_body': None},
                                              {   'alert_field_id': '4a3add3c-5611-4dd9-ba65-4fb60b7f4fc6',
                                                  'template_body': '{{ '
                                                                   'alert.data.email.body '
                                                                   '}}'},
                                              {   'alert_field_id': '45a09cf3-b0f2-43cf-b596-34aaab9279dc',
                                                  'template_body': None}]},
    {   'name': 'Grafana',
        'source_type': 'grafana',
        'alert_urgency_id': '5d357977-9dbe-42ad-b647-5a442cab3d96',
        'deduplicate_alerts_by_key': False,
        'deduplication_key_kind': 'payload',
        'deduplication_key_path': None,
        'deduplication_key_regexp': None,
        'owner_group_ids': [],
        'alert_template_attributes': {   'title': '{{ alert.data.title }}',
                                         'description': '{{ alert.description '
                                                        '}}',
                                         'external_url': ''},
        'alert_source_urgency_rules_attributes': [],
        'sourceable_attributes': None,
        'resolution_rule_attributes': None,
        'alert_source_fields_attributes': [   {   'alert_field_id': '39b50c54-efa8-47fc-acc6-90f1455a8834',
                                                  'template_body': '{{ '
                                                                   'alert.data.title '
                                                                   '}}'},
                                              {   'alert_field_id': '4a3add3c-5611-4dd9-ba65-4fb60b7f4fc6',
                                                  'template_body': '{{ '
                                                                   'alert.description '
                                                                   '}}'},
                                              {   'alert_field_id': '45a09cf3-b0f2-43cf-b596-34aaab9279dc',
                                                  'template_body': ''}]},
    {   'name': 'PIngdom',
        'source_type': 'generic_webhook',
        'alert_urgency_id': '5d357977-9dbe-42ad-b647-5a442cab3d96',
        'deduplicate_alerts_by_key': False,
        'deduplication_key_kind': 'payload',
        'deduplication_key_path': '$.check_id',
        'deduplication_key_regexp': None,
        'owner_group_ids': [],
        'alert_template_attributes': {   'title': '{{ alert.data.check_name '
                                                  '}}: {{ '
                                                  'alert.data.description }}',
                                         'description': 'Long Description: {{ '
                                                        'alert.data.long_description '
                                                        '}}\n'
                                                        '\n'
                                                        'Full URL: {{ '
                                                        'alert.data.check_params.full_url '
                                                        '}}\n',
                                         'external_url': ''},
        'alert_source_urgency_rules_attributes': [   {   'json_path': '$.importance_level',
                                                         'operator': 'is',
                                                         'value': 'LOW',
                                                         'kind': 'payload',
                                                         'alert_urgency_id': 'd7ed8e91-ffa9-4cc4-b524-729d14a4425b'}],
        'sourceable_attributes': {   'id': 'c4a8fbb4-b7c7-4801-a134-bab0358babe0',
                                     'created_at': '2026-03-02T13:56:11.223-08:00',
                                     'updated_at': '2026-03-02T13:56:11.249-08:00',
                                     'field_mappings': [   {   'id': '8bd07e74-2db6-4685-80b5-715cf5193a56',
                                                               'field': 'external_id',
                                                               'json_path': '$.check_id',
                                                               'created_at': '2026-03-02T13:56:11.232-08:00',
                                                               'updated_at': '2026-03-02T13:56:11.232-08:00'},
                                                           {   'id': '7315b0b7-57f6-440b-af9b-27ed6d46d352',
                                                               'field': 'state',
                                                               'json_path': '$.current_state',
                                                               'created_at': '2026-03-02T13:56:11.245-08:00',
                                                               'updated_at': '2026-03-02T13:56:11.245-08:00'}],
                                     'auto_resolve': True,
                                     'resolve_state': 'UP',
                                     'field_mappings_attributes': [   {   'id': '8bd07e74-2db6-4685-80b5-715cf5193a56',
                                                                          'alerts_generic_webhook_source_id': 'c4a8fbb4-b7c7-4801-a134-bab0358babe0',
                                                                          'deleted_at': None,
                                                                          'created_at': '2026-03-02T13:56:11.232-08:00',
                                                                          'updated_at': '2026-03-02T13:56:11.232-08:00',
                                                                          'field': 'external_id',
                                                                          'json_path': '$.check_id'},
                                                                      {   'id': '7315b0b7-57f6-440b-af9b-27ed6d46d352',
                                                                          'alerts_generic_webhook_source_id': 'c4a8fbb4-b7c7-4801-a134-bab0358babe0',
                                                                          'deleted_at': None,
                                                                          'created_at': '2026-03-02T13:56:11.245-08:00',
                                                                          'updated_at': '2026-03-02T13:56:11.245-08:00',
                                                                          'field': 'state',
                                                                          'json_path': '$.current_state'}]},
        'resolution_rule_attributes': {   'id': '78a083da-876c-4c96-b29f-cc77f9226109',
                                          'enabled': True,
                                          'condition_type': 'all',
                                          'identifier_matchable_type': None,
                                          'identifier_matchable_id': None,
                                          'identifier_reference_kind': 'payload',
                                          'identifier_json_path': '$.check_id',
                                          'identifier_value_regex': None,
                                          'conditions_attributes': [   {   'id': '375c8d3b-b4d7-47f1-b973-42e81c91c3d9',
                                                                           'field': '$.current_state',
                                                                           'operator': 'is',
                                                                           'value': 'UP',
                                                                           'conditionable_type': None,
                                                                           'conditionable_id': None,
                                                                           'kind': 'payload'}]},
        'alert_source_fields_attributes': [   {   'alert_field_id': '4a3add3c-5611-4dd9-ba65-4fb60b7f4fc6',
                                                  'template_body': 'Long '
                                                                   'Description: '
                                                                   '{{ '
                                                                   'alert.data.long_description '
                                                                   '}}\n'
                                                                   '\n'
                                                                   'Full URL: '
                                                                   '{{ '
                                                                   'alert.data.check_params.full_url '
                                                                   '}}\n'},
                                              {   'alert_field_id': '45a09cf3-b0f2-43cf-b596-34aaab9279dc',
                                                  'template_body': ''},
                                              {   'alert_field_id': '39b50c54-efa8-47fc-acc6-90f1455a8834',
                                                  'template_body': '{{ '
                                                                   'alert.data.check_name '
                                                                   '}}: {{ '
                                                                   'alert.data.description '
                                                                   '}}'}]}]

ALERT_ROUTES = [   {   'created_at': '2025-05-09T12:30:46.883-07:00',
        'updated_at': '2025-05-09T12:30:46.883-07:00',
        'name': 'Grafana Production Catch-All Route',
        'alerts_source_ids': ['90cda8ea-ff34-4553-b0c3-8744ee74200d'],
        'enabled': True,
        'owning_team_ids': ['9f00e9f1-2f13-470e-a856-50ab5003f260'],
        'rules': [   {   'id': '90fb5bb8-2fc8-44c7-b3cb-2c85d1d5d124',
                         'alerts_source_id': None,
                         'condition_type': 'all',
                         'enabled': True,
                         'destination': {   'target_type': 'EscalationPolicy',
                                            'target_id': '96629210-cc41-4e57-b059-b182a0f01c5b'},
                         'created_at': '2026-03-02T14:26:29.378-08:00',
                         'updated_at': '2026-03-02T14:26:29.378-08:00',
                         'owning_teams': [],
                         'name': 'Fallback Rule for Grafana Production '
                                 'Catch-All Route',
                         'destinations': [   {   'target_type': 'EscalationPolicy',
                                                 'target_id': '96629210-cc41-4e57-b059-b182a0f01c5b'}],
                         'condition_groups': [],
                         'position': 1,
                         'fallback_rule': True}]},
    {   'created_at': '2025-05-09T12:29:21.773-07:00',
        'updated_at': '2025-05-09T12:29:21.773-07:00',
        'name': 'Pingdom Catch-All Route',
        'alerts_source_ids': ['0b59c848-f764-4a31-a90f-1d473cc2b134'],
        'enabled': True,
        'owning_team_ids': ['9f00e9f1-2f13-470e-a856-50ab5003f260'],
        'rules': [   {   'id': '568d73dc-143e-43f9-91a4-ddcd5bf7cf88',
                         'alerts_source_id': None,
                         'condition_type': 'any',
                         'enabled': True,
                         'destination': {   'target_type': 'EscalationPolicy',
                                            'target_id': '96629210-cc41-4e57-b059-b182a0f01c5b'},
                         'created_at': '2026-03-02T14:26:30.071-08:00',
                         'updated_at': '2026-03-02T14:26:30.071-08:00',
                         'owning_teams': [],
                         'name': 'Fallback Rule for Pingdom Catch-All Route',
                         'destinations': [   {   'target_type': 'EscalationPolicy',
                                                 'target_id': '96629210-cc41-4e57-b059-b182a0f01c5b'}],
                         'condition_groups': [],
                         'position': 1,
                         'fallback_rule': True}]},
    {   'created_at': '2025-05-09T11:46:36.220-07:00',
        'updated_at': '2025-05-09T11:46:36.220-07:00',
        'name': 'Platform Engineering Team Email Monitor Route',
        'alerts_source_ids': ['5933666e-e61e-4339-9b39-41756dafdd00'],
        'enabled': True,
        'owning_team_ids': ['9f00e9f1-2f13-470e-a856-50ab5003f260'],
        'rules': [   {   'id': '7dd0a9d0-43e7-4eb0-a2c3-122c2edff1ae',
                         'alerts_source_id': None,
                         'condition_type': 'all',
                         'enabled': True,
                         'destination': {   'target_type': 'Group',
                                            'target_id': '9f00e9f1-2f13-470e-a856-50ab5003f260'},
                         'created_at': '2026-03-02T14:26:30.871-08:00',
                         'updated_at': '2026-03-02T14:26:30.871-08:00',
                         'owning_teams': [],
                         'name': 'Fallback Rule for Platform Engineering Team '
                                 'Email Monitor Route',
                         'destinations': [   {   'target_type': 'Group',
                                                 'target_id': '9f00e9f1-2f13-470e-a856-50ab5003f260'}],
                         'condition_groups': [],
                         'position': 1,
                         'fallback_rule': True}]}]

ESCALATION_POLICIES = [   {   'name': 'Default Escalation Policy',
        'repeat_count': 5,
        'description': '',
        'group_ids': ['9f00e9f1-2f13-470e-a856-50ab5003f260'],
        'service_ids': [   '2cc9bbde-ba8a-4c34-aa85-65f4d9c8aff4',
                           '9fc1b049-d60c-4a4c-b5d9-95ea8db3aae8',
                           'dfc02e84-e281-43a6-b340-0e7cadd62036',
                           'aaede19c-4521-40cd-ab64-6a2d70dd783c',
                           'db3e4db5-fa3f-4239-a0f4-aa558847df66',
                           '24ef3748-0a12-4a55-9b4e-5eb94a08fe03',
                           '964321a2-ebd8-46d4-bd9e-c582cb4e4e49',
                           '6f9bf7d9-d06c-4ac4-8105-f8def1dc91d2',
                           '70173c97-f29d-453f-93ea-da9321d5984d',
                           'e7b42ec2-216d-4e84-828e-97bd709b018b',
                           '8be387cb-2c05-4688-8ea0-730328297d62',
                           '71bb3195-11a8-4a2d-b9b8-2b1dbbc5d6c2',
                           '7b46658d-cd59-4c49-970b-9e9dc8998a7e',
                           '0e8c091d-274d-4687-bb70-d85c5600e90b',
                           'b2389961-09be-4167-a304-a2ee1ef9af1b',
                           '24abd4d9-4aac-4ea0-afc6-eb2106cc52fd',
                           'ffd3bdea-a4f6-4f4a-a12a-f59e71f29fe9',
                           'ce09f262-1edf-475f-b145-3185d0da7241',
                           '0f046ecc-a5eb-4cdf-aba2-6922001ad774',
                           '145db75f-c893-444b-9564-85ff41d42c6a',
                           '3fa021bd-25ba-4732-b588-a304cb1a104f',
                           'aefc0e95-1376-41f2-b102-335a186e9eb7',
                           '6ee39557-47af-40e9-a4f7-eccee9406ecf',
                           'c144023f-00c1-48dd-9e38-ad4c302207e3',
                           'cdceaa06-6690-4351-a3af-dd36bfd6fb55',
                           'defb1faa-e8a4-4fe5-8f03-4103667592f1'],
        'business_hours': {   'time_zone': 'America/New_York',
                              'days': ['F', 'M', 'T', 'R', 'W'],
                              'start_time': '09:00',
                              'end_time': '17:00'}},
    {   'name': 'exampleDeleteMe-EscalationPolicy',
        'repeat_count': 1,
        'description': 'Example escalation policy – safe to delete',
        'group_ids': [],
        'service_ids': [],
        'business_hours': {   'time_zone': None,
                              'days': ['F', 'M', 'T', 'R', 'W'],
                              'start_time': '09:00',
                              'end_time': '17:00'}}]
